### ISSUE TITLE
Document owners management for azuread_application

### ISSUE THREAD

**Issue by jmcshane** [terraform-providers/terraform-provider-azuread#177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Document `azuread_application` owners management, the feature is implemented, but not discussed anywhere on the [website](https://www.terraform.io/docs/providers/azuread/r/application.html).

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

No change to the resource, just documentation update

### References

This feature was implemented in #159, but it looks like that PR didn't update the documentation. I am willing to do the doc PR, but wanted to put a note here first to track the issue.

**Comment by drdamour** [comment]
soemthing i ran into when trying this out...if you are using a SP (probably really any auth method) and you don't include the auth method object id in the owners..then tf will remove the default one and then try to add the others but those will fail because the app will have no owners...kinda a pain.

also owners MUST be users and not groups and there's no easy tf way to get members of a group...

**Comment by katbyte** [comment]
This has been updated in master 🙂  thanks for raising it @jmcshane!

**Comment by jmcshane** [comment]
I just want to commend the team on their handling of this issue and the communication within. Thank you for all you do to support end users of this software!
