### ISSUE TITLE
azuread 0.7.0 and TF 0.12.21 - Error: no available version is compatible with this version of Terraform

### ISSUE THREAD

**Issue by jbobbylopez** [terraform-providers/terraform-provider-azuread#219]
Experiencing a compatibility error with the 'azuread' provider as follows.   I'm using an updated version of terraform, along with v2.0 of azurerm.  

This seems like a bug in the provider on the surface, but I'd like some confirmation.   Is the 'azuread'  0.7.0 provider compatible with either the 0.12.20 or 0.12.21 versions of terraform?
```
$  terraform init
Initializing modules...
- azure_app in ../../../application
- azure_sp in ../..

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

No available provider "azure" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.

- Downloading plugin for provider "azurerm" (hashicorp/azurerm) 2.0.0...
- Downloading plugin for provider "azuread" (hashicorp/azuread) 0.7.0...

Error: no available version is compatible with this version of Terraform

# And the terraform version
 $  terraform version
Terraform v0.12.21
```

**Comment by tombuildsstuff** [comment]
hi @jbobbylopez 

Taking a look at the error being returned here:

> No available provider "azure" plugins are compatible with this Terraform version.

It appears you're attempting to use the deprecated `azure` provider when I believe you want to be using the `azurerm` provider - would you be able to take a look and see if updating the Terraform Configuration to use the AzureRM Provider instead works for you?

Since this should be fixed by using the `azurerm` provider rather than the deprecated `azure` (service management) provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
