### ISSUE TITLE
azuread_application; adding owner removes SP ownership from App Registration

### ISSUE THREAD

**Issue by RavulaChetan** [terraform-providers/terraform-provider-azuread#234]
When using azuread_application, owner attribute to add owner to App Registration. The Service Principal creating the app registration is removed from owner of the app registration.

Example; azuread_application executed using SP XXXX

resource "azuread_application" "service_auth" {
  name     = "sample-app"
  homepage = "www.google.com"
  owners   = ["${var.client_id}"]

Doing the above adds the user with client_id as owner but the SP that created this app registration is no more the owner. 
This cause issues when other actions are run on the app registration.

**Comment by katbyte** [comment]
@RavulaChetan - this is because you're over-writing the default owner. terraform doesn't know you don't want to overwrite it so you'll need to add the SP to the owners property along with the client id.

**Comment by manicminer** [comment]
Hi @RavulaChetan, as mentioned you would need to specify the complete list of owners for this property in order to get the behavior you want. If the original owning service principal is being created outside of Terraform, you should be able to look up the object ID using the [azuread_service_principal data source](https://www.terraform.io/docs/providers/azuread/d/service_principal.html).
