### ISSUE TITLE
azurerm_kubernetes_cluster service_principal or identity still requires service_principal

### ISSUE THREAD

**Issue by CasperNaudts** [terraform-providers/terraform-provider-azuread#241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v0.12.24
+ provider.azurerm v2.0.0
```

### Affected Resource(s)
* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
    name                = "research-k8s"
    location            = azurerm_resource_group.k8s.location
    resource_group_name = azurerm_resource_group.k8s.name
    dns_prefix          = "research"
    kubernetes_version  = "1.16.7"

    default_node_pool {
        name       = "agentpool"
        vm_size    = "Standard_B2s"
        enable_auto_scaling = true
        max_count  = 3
        min_count  = 1
    }

    identity {
        type = "SystemAssigned"
    }

    tags = {
        Project = "Research"
    }
}
```

### Expected Behavior

One of either identity or service_principal must be specified.

### Actual Behavior

service_principal is a required field

### Steps to Reproduce

1. `terraform plan or apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @CasperNaudts 

Thanks for opening this issue.

Support for Service Principal-less clusters is available in a newer version of the Azure Provider - we're currently on version v2.5.0 - which you can upgrade to by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "= 2.5.0"
}
```

.. which should solve this for you.

Since this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
