### ISSUE TITLE
Cannot authorize to azuread with a Service Principal without a Subscription

### ISSUE THREAD

**Issue by piotrgwiazda** [terraform-providers/terraform-provider-azuread#259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

terraform 0.12.24
azuread 0.9.0

### Affected Resource(s)

Provider configuration

### Terraform Configuration Files

```hcl
provider "azuread" {
   tenant_id="X"
   version="=0.9.0"
}
```

### Debug Output

"A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret"

### Panic Output

N/A

### Expected Behavior

I have an AAD Tenant with no subscriptions. I'd like to authenticate using a Service Principal to create user groups in this AAD.

### Actual Behavior

Error says : "A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret"

### Steps to Reproduce

1. Have a free tier Azure AD. **Do not have any subscriptions attached**
2. Create a Service Principal
3. Set ACR_* environment variables to authorize as a Service Principal
4. `terraform init`
5. `terraform plan`

### Important Factoids

I have tried using `az login --service-principal` before running terraform. The error says that only user accounts can be used with `az login`.

### References

N/A

* #0000

**Comment by manicminer** [comment]
Hi @piotrgwiazda, in order to access an Azure Active Directory without an associated subscription, you will need to set the subscription ID in your configuration to be the same as the tenant ID. For example, if you're configuring via environment variables:

```sh
export ARM_TENANT_ID=10000000-2000-3000-4000-500000000000
export ARM_SUBSCRIPTION_ID=${ARM_TENANT_ID}
```

I will look at improving documentation for this scenario.

**Comment by piotrgwiazda** [comment]
Thank you. I will try that. 
By the way, following this scenario, is it possible to use a different Service Principal in a different tenant to connect to the Azure terraform backend? It tries to use the same env variables for backend and provider.
I was partially sucessful using SAS token for the backend, but maybe there is a scenario for that.

**Comment by manicminer** [comment]
In theory you should be able to register an Application and link Service Principals in multiple tenants, but I've never tried it and I'm not sure permissions will carry in the way you might need. It's definitely simpler to use an application/SP per tenant.

**Comment by piotrgwiazda** [comment]
I gave up on configuring a multi-tenant application already. Now I am stuck on passing two different SP credentials for the backend and for the provider.

**Comment by imbatman4711** [comment]
I am currently using the approach of authenticating against multiple tenants. I use the client authentication for my main tenant and the service principal to authenticate against the second tenant. You need to create seperate providers and distinguish them by alias, then you may use them in the respective tasks.

**Comment by manicminer** [comment]
@imbatman4711 do you perhaps have any example configuration we might be able to use?

**Comment by imbatman4711** [comment]
Sure,

so i have two different provider configurations
The first one is using my azure cli login:

```
provider "azuread" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=0.9.0"
  #replace with your subscriptionid
  subscription_id = "000000000-0000-0000-0000-000000000000"
  #replace with your tenantid
  tenant_id       = "000000000-0000-0000-0000-000000000000"
  environment = "public"
  alias  = "yourealiasgoeshere"
}
```

The second is defined in a different file that is put on gitignore to avoid accidental push to git.

```
provider "azuread" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=0.9.0"
  #replace with your application id
  client_id       = "000000000-0000-0000-0000-000000000000"
  client_secret   = "superSecretPasswordGeneratedByAzure"
  # subscription inside of the main tenant
  # need to be here even that it is not used
  subscription_id = "000000000-0000-0000-0000-000000000000"
  # your tenant
  tenant_id       = "000000000-0000-0000-0000-000000000000"
  environment = "public"
  alias  = "anotheralias"
}
```

With this configuration you are able to decide in which tenant the commands will be executed by defining the provider to be used:

```
resource "azuread_group" "group-in-first-tenant" {
  provider = azuread.yourealiasgoeshere
  name = "superFancyGroup"
}

resource "azuread_group" "group-in-second-tenant" {
  provider = azuread.anotheralias
  name = "superFancyGroup"
}
```

Off course, you should be able to define the service principal authentication in both providers. I think the documentation is quite helpful on that. Sadly (i would consider this as a bug) even if you use a tenant without subscription, you need to define one but it is not used.

Our situation is that we have our company tenant that holds the subscription. For a specific client we have created an AAD instance and use it for authentication purposes of our application (to avoid messing around with our own AAD). Therefore the resources are created in our corporate tenant but in addition I need to create service users in the additional tenant.

WARNING: You should always define which provider to be used because I am not sure about the behavior (if the last used is taken if nothing is defined or the first one).

I hope that helps.

**Comment by manicminer** [comment]
@imbatman4711 thanks, that makes sense. I didn't read properly at first that you are using CLI auth for one tenant and SP auth in the other :)

**Comment by imbatman4711** [comment]
@manicminer i assume that the same approach will work if you use SP auth on both cases. Not sure what happens if you use a single SP and invite it in the second tenant. But with different SP this schould work as described above.

**Comment by piotrgwiazda** [comment]
@imbatman4711 the thing is you have a secret in the second provider code. You probably use some smart way not to have it in Git. Correct?

Also CLI auth works with terraform only for "human" accounts with interactive login page. If you "az login" with SP, Terraform will won't allow to proceed and tell you to use ARM_CLIENT_ID and ARM_SECRET env variables. If gou use them, they will be picked by both providers.

Also, how does you backend config look like? Do you pass backend params in commandline?

**Comment by imbatman4711** [comment]
@piotrgwiazda  Youre right, that is one of two disadvantages that the approach comes with. In order to avoid these secrets in git we have defined a seperate file calles 00-provider.tf that is put on gitignore. In the readme (that is pushed to git) there is a template for this file.

Because of the second issue which is that you are not able to tell who did something on the cloud if you use non personal account, we also defined that any admin will create its own service principal in the second tenant. With this approach you will be able to see who issued something and avoid storing the credentials in git.

In order to avoid that the state needs to be pushed to git, we use a storage account within the backend configuration.

```
terraform {
 backend "azurerm" {
    # sadly, no variables are allowed inside
    resource_group_name  = "super-fancy-resource-group"
    storage_account_name = "sfstorage"
    container_name       = "super-fancy-container"
    key                  = "terraform.tfstate"
 }
}
```

So the main process to start from scratch 

- checkout terraform code
- execute cli script to provision resource group for permanent resources (including the storage acount, also you need to set the az login to the subscription that hold the storage account)
- create provider file
- create service principal in second tenant
- insert details into provider configuration
- execute terraform

The permanent resources resource group is beeing used for things that must not be deleted like IP Addresses, KeyVaults, VirtualNetwork and then we are using resourcegroups to seperate environments that use these resources.

**Comment by manicminer** [comment]
The next release of the provider will no longer require a subscription ID to be set. Documentation will also be updated to reflect this, and to clarify some aspects of configuration and setting up permissions. See https://github.com/terraform-providers/terraform-provider-azuread/pull/271

I'm going to close this for now. If anyone has specific requirements for cross-tenant authentication and other scenarios, please feel free to open a new issue. Thanks to all for the valuable discussion!
