### ISSUE TITLE
data.azuread_groups: using a wildcard filter

### ISSUE THREAD

**Issue by chiokejjones** [terraform-providers/terraform-provider-azuread#293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_groups

### Use Case

Retrieve multiple groups that match the given filter.

#### Current HCL

```hcl
data "azuread_groups" "groups" {
  names = ["group-a", "group-b"]
}
```

#### Requesting Feature HCL
```hcl
data "azuread_groups" "groups" {
  names = ["foo-*"]
}
```

### References

* https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/groups

**Comment by manicminer** [comment]
Hi @chiokejjones, thanks for requesting this! Could you give more detail on your use case for this functionality?

**Comment by chiokejjones** [comment]
Hey @manicminer. Thanks for following up. In my specific use case, I'd like to retrieve all Azure AD groups whose display name starts with a specific prefix; i.e retrieve all groups that start with "GCP".  The current azuread_groups data resource requires defining the complete group name in order to retrieve information from Azure AD.

**Comment by manicminer** [comment]
Hi @chiokejjones, thanks for clarifying. Just letting you know I'm still thinking through this and how it might extend to other resources.

**Comment by manicminer** [comment]
Hi @chiokejjones, on balance this doesn't feel like a good fit for Terraform. Data sources are intended to be explicit lookups rather than search tools. Applying broad changes to existing objects based on their prefix is something perhaps better suited to a script. If we were to enable broad searching using data sources it could lead to unexpected and inconsistent results when using those results to apply coinfigurations. Accordingly I'm going to close this request as we won't implement this.
