### ISSUE TITLE
public_client defaults to true for type=native

### ISSUE THREAD

**Issue by jbentleyKroger** [terraform-providers/terraform-provider-azuread#333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

TF: 0.13.3. 
AzureRM : 2.30.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
# Script 1:
resource "azuread_application" "appname" {
  name                       = "appname
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
  homepage = "https://obscured"
  identifier_uris = []
  reply_urls = ["msauth://package/signature"]
  type = "native"
  group_membership_claims = "All"
  required_resource_access {
    resource_app_id = "..."
    resource_access {
      id   = "..."
      type = "Scope"
    }
  }
  owners = [] 
}
Script 2:
resource "azuread_application" "appname" {
  name                       = "appname
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
  homepage = "https://obscured"
  identifier_uris = []
  reply_urls = ["msauth://package/signature"]
  type = "native"
  group_membership_claims = "All"
  public_client="false"
  required_resource_access {
    resource_app_id = "..."
    resource_access {
      id   = "..."
      type = "Scope"
    }
  }
  owners = [] 
}
```

### Expected Behavior

When executing Script 1, the 'allowPublicClient' field, in the created app registration, should have been set to false per documentation.

When executing Script 2, 'allowPublicClient' should be set to false and no other properties should be affected.

### Actual Behavior

When executing Script 1, 'allowPublicClient' is set to true, in the app registration's manifest.

When executing Script 2, 'allowPublicClient' is set to false. However, the type (specified in the 'replyUrlsWithType' object) is changed from 'InstalledClient' to 'web' in the app registration's manifest. This suggests that the type argument is overridden/ignored when the public_client argument is specified.

In Azure, when a native app is registered, 'allowPublicClient' is actually set to null.  It appears that there should be parity here, allowing 'true', 'false' and 'null', with default being null. Either the documentation must be updated to describe the side-effect of specifying public_client when type=native, or the arguments should be able to be specified independently.

### Steps to Reproduce

1. `terraform apply`

### References

* documentation: https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application

**Comment by manicminer** [comment]
Hi @jbentleyKroger, thanks for raising this. Unfortunately the behavior you observed is due to the [Azure Active Directory Graph] API we currently use. There are a number of limitations with respect to allowPublicClient and reply/redirect URIs which stem from upgrades to the application manifest schema which did not get translated into the API. The concept of "native" versus "web" application types no longer applies in Azure, but the API is frozen in time before this.

In order to provide any functionality around "native" applications (i.e. having any support for public clients) we are forced to do the following:
- when type == "web", we can set redirectUris but they can only be of type "web"
- when type == "native", we cannot set redirectUris (the API force-clears them), and the [deprecated] enablePublicClient field is set to true
- this is compounded by SDK flaws leaving us unable to set any field values to null

We are moving towards the newer Microsoft Graph API, and our own SDK, which does/will not suffer these limitations (and as a result the provider schema for applications will change accordingly). You can track this progress in #323 

I hope this helps with planning your configuration, and determining the limits of what you can currently manage in your app manifests with the provider. Since this issue is pretty much the same as #236, I'm going to go ahead close this in favor of that issue.
