### ISSUE TITLE
New Data Source/Resource: `azuread_user`

### ISSUE THREAD

**Issue by glenjamin** [terraform-providers/terraform-provider-azuread#8]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using `azurerm_role_assignment` to set permissions, we often want to refer to existing users and groups.

It would be great if there was a data provider for this.

It might also be useful to have a resource provider to create these in the first place.

### New or Affected Resource(s)

n/a

### Potential Terraform Configuration

n/a

### References

n/a

**Comment by perbergland** [comment]
Since it seems this will be implemented fairly soon I have been thinking about how to treat group members and owners.
For most use cases I would prefer to be able to add both owners and members outside of terraform so then it would make the most sense to have group members and owners as resources separate from the group itself, but sometimes I want to have fully managed groups and then it would be preferred to have both properties as lists and purge any item not mentioned in the list.

What are other people's thoughts?

**Comment by tombuildsstuff** [comment]
@perbergland I'd suggest opening a separate issue for that (tbh this issue should be split into two, one for the Groups and one for Users since both of these areas are pretty big, but anyway 🙃). 

In terms of how that's implemented I could see it being useful to manage both internally and externally as you've mentioned; but I'd suggest it needs further research as to the API's available in that new issue?

**Comment by tombuildsstuff** [comment]
Support for Groups has been merged in #14 (thanks @tiwood 🍾) - as such I'm going to update the title of this issue to focus on support for Users (which is being added in #18)

**Comment by katbyte** [comment]
Support for users was merged in #18 (thanks again @tiwood)
